# This action sets up the BFASST environment in order to run other tools
# TODO: Use https://github.com/actions/cache to cache rapidwright tool 

name: "Setup Environment"
runs:
  using: "composite"
  steps:
  
  - name: venv
    shell: bash
    run: |
      make venv
      make python_packages

  - name: rapidwright
    shell: bash
    run: | 
      make rapidwright
      
  - name: env
    shell: bash
    run: |
      make env

  - name: fasm2bels
    shell: bash
    run: |
      make install_fasm2bels

  - name: fasm2bels_artifcats
    if: always()
    uses: actions/upload-artifact@v3
    with:
      name: log_files
      path: |
        build/**/log.txt

  - name: wafove
    shell: bash
    run: |
      make install_wafove
    
          
